// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/TestInfo.vue')['default']
    TestInfo: typeof import('./src/components/TestInfo.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VBtn: typeof import('vuetify/components')['VBtn']
  }
}

export {}
