// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyScrool: typeof import('./components/MyScrool.vue')['default']
    RoleCard: typeof import('./components/RoleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheContainer: typeof import('./components/TheContainer.vue')['default']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCol: typeof import('vuetify/components')['VCol']
    VImg: typeof import('vuetify/components')['VImg']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VRow: typeof import('vuetify/components')['VRow']
    VTab: typeof import('vuetify/components')['VTab']
    VTabs: typeof import('vuetify/components')['VTabs']
    VWindow: typeof import('vuetify/components')['VWindow']
    VWindowItem: typeof import('vuetify/components')['VWindowItem']
  }
}

export {}
