// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigDialogProject: typeof import('./components/ConfigDialogProject.vue')['default']
    ConfigDialogRole: typeof import('./components/ConfigDialogRole.vue')['default']
    InputDialogAddGroup: typeof import('./components/InputDialogAddGroup.vue')['default']
    InputDialogAddRole: typeof import('./components/InputDialogAddRole.vue')['default']
    InputDialogCreateProject: typeof import('./components/InputDialogCreateProject.vue')['default']
    InputDialogCreateRole: typeof import('./components/InputDialogCreateRole.vue')['default']
    InputDialogCreateRound: typeof import('./components/InputDialogCreateRound.vue')['default']
    MyScrool: typeof import('./components/MyScrool.vue')['default']
    NewRoleCard: typeof import('./components/NewRoleCard.vue')['default']
    RoleCard: typeof import('./components/RoleCard.vue')['default']
    RoleInfoCard: typeof import('./components/RoleInfoCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheContainer: typeof import('./components/TheContainer.vue')['default']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAutocomplete: typeof import('vuetify/components')['VAutocomplete']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardSubtitle: typeof import('vuetify/components')['VCardSubtitle']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    ViewRoundCards: typeof import('./components/ViewRoundCards.vue')['default']
    ViewRoundWindow: typeof import('./components/ViewRoundWindow.vue')['default']
    VImg: typeof import('vuetify/components')['VImg']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListGroup: typeof import('vuetify/components')['VListGroup']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/components')['VProgressLinear']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VSwitch: typeof import('vuetify/components')['VSwitch']
    VTextField: typeof import('vuetify/components')['VTextField']
    VWindow: typeof import('vuetify/components')['VWindow']
  }
}

export {}
