// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InputDialogAddCharacter: typeof import('./components/InputDialogAddCharacter.vue')['default']
    InputDialogAddGroup: typeof import('./components/InputDialogAddGroup.vue')['default']
    InputDialogCreateActivity: typeof import('./components/InputDialogCreateActivity.vue')['default']
    InputDialogCreateCharacter: typeof import('./components/InputDialogCreateCharacter.vue')['default']
    InputDialogCreateRound: typeof import('./components/InputDialogCreateRound.vue')['default']
    MyScrool: typeof import('./components/MyScrool.vue')['default']
    NewRoleCard: typeof import('./components/NewRoleCard.vue')['default']
    RoleCard: typeof import('./components/RoleCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheContainer: typeof import('./components/TheContainer.vue')['default']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAutocomplete: typeof import('vuetify/components')['VAutocomplete']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDialog: typeof import('vuetify/components')['VDialog']
    VFileInput: typeof import('vuetify/components')['VFileInput']
    ViewRoundCards: typeof import('./components/ViewRoundCards.vue')['default']
    ViewRoundTabs: typeof import('./components/ViewRoundTabs.vue')['default']
    VImg: typeof import('vuetify/components')['VImg']
    VLayout: typeof import('vuetify/components')['VLayout']
    VList: typeof import('vuetify/components')['VList']
    VListGroup: typeof import('vuetify/components')['VListGroup']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    VProgressCircular: typeof import('vuetify/components')['VProgressCircular']
    VRow: typeof import('vuetify/components')['VRow']
    VSelect: typeof import('vuetify/components')['VSelect']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VTab: typeof import('vuetify/components')['VTab']
    VTabs: typeof import('vuetify/components')['VTabs']
    VTextField: typeof import('vuetify/components')['VTextField']
    VWindow: typeof import('vuetify/components')['VWindow']
    VWindowItem: typeof import('vuetify/components')['VWindowItem']
  }
}

export {}
